pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
pip install tensorboard
pip install tensorboardX
pip install timm
pip install einops
pip install yacs
pip install transformers
pip install pymarlin
pip install torchnet
pip install imageio
pip install timm==0.4.12
pip install deepspeed==0.5.8
pip install TensorboardX
pip install decord
pip install einops
pip install pytorchvideo
pip install opencv-python-headless
pip install mmcv
pip install pathlib
pip install mmcv-full
pip install ftfy
pip install termcolor
pip install regex
pip install scikit-learn
pip install psutil
pip install simplejson
pip install 'git+https://github.com/facebookresearch/fvcore'
pip install matplotlib
